mex ZBufferC.cpp ...
    -I'/usr/include' ...
    -I'/usr/include/opencv' ...
    -I'/usr/include/opencv2' ...
    -L'/usr/local/lib' ...
    -l'opencv_core'...
    ModalAndRef.cpp 
    
    
